'use client'

import { useRef, useState } from 'react'
import { motion, useInView, AnimatePresence } from 'framer-motion'
import { PhaseWrapper } from '../shared/PhaseWrapper'
import { CollapsibleSection } from '../shared/CollapsibleSection'
import { SourceCitation, SourceCitationGroup } from '../shared/SourceCitation'
import { Key, Copy, CheckCircle, ExternalLink, Fingerprint, AlertCircle, Info, Clock, Coins } from 'lucide-react'

const THE_1CFB_ADDRESS = '1CFBdvaiZgZPTZERqnezAtDQJuGHKoHSzg'

interface AddressSegment {
  text: string
  color: string
  label: string
  description: string
}

// All segments with detailed hover descriptions
const addressSegments: AddressSegment[] = [
  {
    text: '1',
    color: 'text-[#D4AF37]',
    label: 'Network',
    description: 'This "1" means it\'s a real Bitcoin address on the main network (not a test)',
  },
  {
    text: 'CFB',
    color: 'text-[#D4AF37]',
    label: 'Signature',
    description: '"CFB" stands for "Come-From-Beyond" - a famous cryptographer who created multiple blockchain projects',
  },
  {
    text: 'dva',
    color: 'text-[#D4AF37]',
    label: 'Language',
    description: '"dva" means "two" in Russian - a hint about the creator\'s Eastern European origins',
  },
  {
    text: 'i',
    color: 'text-white/40',
    label: 'Separator',
    description: 'A simple separator between the meaningful parts of this address',
  },
  {
    text: 'ZgZ',
    color: 'text-[#D4AF37]',
    label: 'Mirror Pattern',
    description: 'This is a palindrome (reads same forwards and backwards) - intentional symmetry',
  },
  {
    text: 'PTZ',
    color: 'text-[#D4AF37]',
    label: 'Location Hint',
    description: 'Possibly "Petrozavodsk" - a city in Russia. Could reveal the creator\'s hometown',
  },
  {
    text: 'ERqnezAtDQJuGHKoHS',
    color: 'text-white/50',
    label: 'Checksum',
    description: 'This cryptographic portion is generated by Bitcoin\'s algorithm - not chosen by the creator',
  },
  {
    text: 'zg',
    color: 'text-[#D4AF37]',
    label: 'Closing Mirror',
    description: 'Mirrors the earlier "ZgZ" pattern - deliberate bookend symmetry in the address',
  },
]

export function Phase05_TheFirstClue() {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: false, amount: 0.3 })
  const [copied, setCopied] = useState(false)
  const [activeSegment, setActiveSegment] = useState<number | null>(null)

  const copyAddress = async () => {
    await navigator.clipboard.writeText(THE_1CFB_ADDRESS)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <PhaseWrapper
      id="first-clue"
      phaseNumber={5}
      title="The First Clue"
      subtitle="A Bitcoin address that started the investigation"
    >
      <div ref={ref} className="space-y-8">
        {/* The 1CFB Address Display */}
        <motion.div
          className="p-6 md:p-8 rounded-2xl bg-gradient-to-b from-[#050505] to-black/50 border border-orange-500/20 relative overflow-hidden"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 20 }}
          transition={{ duration: 0.5 }}
        >
          {/* Fingerprint watermark */}
          <div className="absolute top-4 right-4 opacity-10">
            <Fingerprint className="w-16 h-16 text-[#D4AF37]" />
          </div>

          <div className="flex items-center gap-3 mb-4">
            <Key className="w-6 h-6 text-[#D4AF37]" />
            <h3 className="text-xl font-bold text-white/90">Block 264 - The Discovery</h3>
          </div>

          <p className="text-white/70 mb-6">
            In early Bitcoin Block #264, researchers found an address that seems to spell out a
            name. <span className="text-[#D4AF37]">Hover or tap each segment</span> to decode its meaning.
          </p>

          {/* Interactive Address Display - HOVER EACH SEGMENT */}
          <div className="p-4 md:p-6 bg-black/40 border border-white/10 mb-4">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs text-white/40 font-mono">Bitcoin Address (Block 264)</span>
              <button
                onClick={copyAddress}
                className="flex items-center gap-1 text-xs text-white/60 hover:text-white/90 transition-colors"
              >
                {copied ? (
                  <>
                    <CheckCircle className="w-3 h-3 text-[#D4AF37]" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-3 h-3" />
                    Copy
                  </>
                )}
              </button>
            </div>

            {/* Segmented Address with Hover */}
            <div className="flex flex-wrap justify-center items-center gap-0">
              {addressSegments.map((segment, index) => (
                <motion.span
                  key={index}
                  className={`font-mono text-lg sm:text-xl md:text-2xl cursor-pointer transition-all duration-200 ${segment.color} ${
                    activeSegment === index
                      ? 'bg-white/20  px-1 scale-110 shadow-lg'
                      : 'hover:bg-white/10 hover:rounded'
                  }`}
                  onMouseEnter={() => setActiveSegment(index)}
                  onMouseLeave={() => setActiveSegment(null)}
                  onClick={() => setActiveSegment(activeSegment === index ? null : index)}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 10 }}
                  transition={{ duration: 0.3, delay: 0.1 + index * 0.05 }}
                  whileHover={{ scale: 1.08 }}
                  whileTap={{ scale: 0.95 }}
                >
                  {segment.text}
                </motion.span>
              ))}
            </div>
          </div>

          {/* Active Segment Info Panel */}
          <div className="min-h-[100px] p-4 bg-black/30 border border-white/5">
            <AnimatePresence mode="wait">
              {activeSegment !== null && addressSegments[activeSegment] ? (
                <motion.div
                  key={activeSegment}
                  initial={{ opacity: 0, y: 5 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -5 }}
                  transition={{ duration: 0.2 }}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <span className={`font-mono text-xl font-bold ${addressSegments[activeSegment].color}`}>
                      {addressSegments[activeSegment].text}
                    </span>
                    <span className="text-xs px-2 py-1 rounded-full bg-white/10 text-white/60">
                      {addressSegments[activeSegment].label}
                    </span>
                  </div>
                  <p className="text-sm text-white/70 leading-relaxed">
                    {addressSegments[activeSegment].description}
                  </p>
                </motion.div>
              ) : (
                <motion.div
                  key="default"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="text-center py-2"
                >
                  <div className="flex items-center justify-center gap-2 text-sm text-white/50 mb-2">
                    <Info className="h-4 w-4" />
                    Tap or hover on each colored segment to decode its meaning
                  </div>
                  <p className="text-xs text-white/30">
                    This address was deliberately crafted to contain hidden information
                  </p>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </motion.div>

        {/* Key Facts */}
        <motion.div
          className="grid grid-cols-2 md:grid-cols-4 gap-3"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 20 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          <div className="p-4 bg-white/5 border border-white/10 text-center">
            <Clock className="h-5 w-5 text-[#D4AF37] mx-auto mb-2" />
            <div className="font-mono text-lg text-white/80">2009</div>
            <div className="text-xs text-white/40">Created</div>
          </div>
          <div className="p-4 bg-white/5 border border-white/10 text-center">
            <Coins className="h-5 w-5 text-[#D4AF37] mx-auto mb-2" />
            <div className="font-mono text-lg text-white/80">50 BTC</div>
            <div className="text-xs text-white/40">Received</div>
          </div>
          <div className="p-4 bg-white/5 border border-white/10 text-center">
            <Fingerprint className="h-5 w-5 text-[#D4AF37] mx-auto mb-2" />
            <div className="font-mono text-lg text-[#D4AF37]">Untouched</div>
            <div className="text-xs text-white/40">17 years</div>
          </div>
          <div className="p-4 bg-white/5 border border-white/10 text-center">
            <Key className="h-5 w-5 text-[#D4AF37] mx-auto mb-2" />
            <div className="font-mono text-lg text-white/80">12</div>
            <div className="text-xs text-white/40">1CFB addresses</div>
          </div>
        </motion.div>

        {/* Verification Link */}
        <motion.a
          href={`https://blockchair.com/bitcoin/address/${THE_1CFB_ADDRESS}`}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center justify-center gap-2 p-4 bg-[#D4AF37]/10 border border-orange-500/20 hover:bg-[#D4AF37]/20 transition-colors"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 20 }}
          transition={{ duration: 0.5, delay: 0.3 }}
        >
          <ExternalLink className="w-4 h-4 text-[#D4AF37]" />
          <span className="text-[#D4AF37] font-medium">Verify on Blockchain Explorer</span>
        </motion.a>

        {/* Additional 1CFB Addresses */}
        <CollapsibleSection
          title="All 12 1CFB Addresses Found"
          icon={<Fingerprint className="w-4 h-4" />}
          badge="Research Finding"
        >
          <div className="space-y-4">
            <div className="flex items-start gap-2 p-3 bg-[#D4AF37]/10 border border-yellow-500/20">
              <AlertCircle className="w-5 h-5 text-[#D4AF37] shrink-0 mt-0.5" />
              <p className="text-sm text-white/70">
                Through systematic derivation from the Anna Matrix (128x128 = 16,384 positions), we
                found <span className="text-[#D4AF37] font-bold">12 total addresses</span>{' '}
                starting with "1CFB" in Bitcoin's early blocks.
              </p>
            </div>

            <div className="p-3 bg-black/30 font-mono text-xs text-white/60 max-h-40 overflow-y-auto space-y-1">
              <div>1CFBdvaiZgZPTZERqnezAtDQJuGHKoHSzg <span className="text-[#D4AF37]">(Block 264)</span></div>
              <div>1CFBtCo6zDgmXAD9NJTZ7dw7Yvoq6ZPGGQ</div>
              <div>1CFBuaBgz1BjLQVfUtaoWBZ58SkCZk1Wnc</div>
              <div>1CFBsY4EvUYox9rxrfWiRvoANtMw8Hr6cn</div>
              <div>1CFBa8L8PpH9zLtt42x6w2d2jids3bYGga</div>
              <div>1CFBjSVcKwVmsLJeKAmHcZUpiFjBZchPDV</div>
              <div>1CFB7LJp1JrHyZAsYBGtQHQBv4nrYv8JTY</div>
              <div className="text-white/40">... and 5 more</div>
            </div>

            <p className="text-xs text-white/40">
              All addresses can be independently verified on any Bitcoin block explorer.
            </p>
          </div>
        </CollapsibleSection>

        <SourceCitationGroup>
          <SourceCitation
            href="/docs/03-results/01-bitcoin-bridge"
            title="The Data Bridge"
            tier={1}
          />
          <SourceCitation
            href="/docs/03-results/40-1cf-census"
            title="1CFB Address Census"
            tier={1}
          />
          <SourceCitation
            href={`https://blockchair.com/bitcoin/address/${THE_1CFB_ADDRESS}`}
            title="Block Explorer"
            external
          />
        </SourceCitationGroup>
      </div>
    </PhaseWrapper>
  )
}
